export enum UserStatus {
  INITIAL = "INITIAL",
  PENDING = "PENDING",
  CONFIRMED = "CONFIRMED",
  REJECTED = "REJECTED",
}

export enum UserRole {
  USER = "USER",
  ADMIN = "ADMIN",
}

export enum TaskStatus {
  ACTIVE = "ACTIVE",
  URGENT = "URGENT",
  PAST_DUE = "PAST DUE",
  COMPLETE = "COMPLETE",
  DISCARDED = "DISCARDED",
}

export enum SolidIcon {
  FORWARD = "FORWARD",
  BACKWARD = "BACKWARD",
  SUCCESS = "SUCCESS",
  WARNING = "WARNING",
  DANGER = "DANGER",
  ADD = "ADD",
  SUBTRACT = "SUBTRACT",
  SET_COMPLETE = "SET_COMPLETE",
  EDIT = "EDIT",
  DUE = "DUE",
  GROUP = "GROUP",
  BACKEND = "BACKEND",
  FRONTEND = "FRONTEND",
  DESIGN = "DESIGN",
  DATABASE = "DATABASE",
  INFRASTRUCTURE = "INFRASTRUCTURE",
  SOFTSKILLS = "SOFTSKILLS",
  LIGHT_THEME = "LIGHT_THEME",
  DARK_THEME = "DARK_THEME",
  FILE_DOWNLOAD = "FILE_DOWNLOAD",
  DOWNLOAD = "DOWNLOAD",
}
